# Match with my local Node Version
FROM node:16-alpine

WORKDIR /app
ADD . /app/

COPY . .
# Dependency Install
RUN rm -rf node_modules
RUN npm install

# 항상 dist갱신
RUN rm -rf dist 
RUN npm run build

# PORT (8080) Expose
EXPOSE 8080

# START
ENTRYPOINT npm run start:prod